name: fbde
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - colorama=0.4.6
  - decorator=5.1.1
  - executing=0.8.3
  - flit-core=3.6.0
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - libffi=3.3
  - libgfortran4=7.5.0
  - libuuid=1.0.3
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.10.4
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - six=1.16.0
  - sqlite=3.39.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing_extensions=4.4.0
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - aif360==0.5.0
    - certifi==2022.6.15
    - contourpy==1.0.7
    - cycler==0.11.0
    - fonttools==4.38.0
    - ipython==8.4.0
    - jedi==0.18.1
    - kiwisolver==1.4.4
    - matplotlib==3.6.3
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - numpy==1.22.4
    - packaging==23.0
    - pandas==1.5.3
    - pillow==9.4.0
    - pip==22.1.2
    - pot==0.8.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - scikit-learn==1.1.1
    - scipy==1.7.3
    - setuptools==61.2.0
    - torch==1.13.1
    - threadpoolctl==3.1.0
    - typing-extensions==4.4.0
